[package]
authors = ["Geoffroy Couprie <contact@geoffroycouprie.com>"]
edition = "2018"
name = "generic-http-client"
version = "0.1.0"

[dependencies]
http = "*"
httparse = "*"
url = "*"
hex = "*"
rustls = "*"
webpki = "*"
webpki-roots = "*"
